spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: auth
          uri: http://localhost:9080/
          predicates:
              - Path=/auth/**
              # =====================================
        - id: payment
          uri: http://localhost:9081/
          predicates:
              - Path=/payment/**
              # =====================================
        - id: stock
          uri: http://localhost:9082/
          predicates:
              - Path=/stock/**
              # =====================================
        - id: basket
          uri: http://localhost:9083/
          predicates:
              - Path=/basket/**
              # =====================================
server:
  port: 9079
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/