server:
  port: 9081

spring:
  cloud:
    discovery:
      enabled: true
  main:
    allow-circular-references: true
  application:
    name: payment
  datasource:
    url: jdbc:mysql://localhost:3306/payment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 17176hasan
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

